module.exports =
[
"Hubei,China",
",Italy",
",Iran",
",Spain",
",Germany",
"France,France",
",Korea, South",
"New York,US",
",Switzerland",
"United Kingdom,United Kingdom",
"Netherlands,Netherlands",
",Austria",
",Belgium",
",Norway",
",Sweden",
"Guangdong,China",
"Washington,US",
"Henan,China",
"Zhejiang,China",
"Denmark,Denmark",
"Hunan,China",
"Anhui,China",
"California,US",
"Jiangxi,China",
",Japan",
",Malaysia",
",Portugal",
"Shandong,China",
"New Jersey,US",
"Diamond Princess,Cruise Ship",
",Czechia",
",Israel",
"Jiangsu,China",
",Brazil",
"Chongqing,China",
",Ireland",
"Sichuan,China",
"Heilongjiang,China",
"Beijing,China",
",Qatar",
",Pakistan",
"Illinois,US",
",Greece",
"Florida,US",
",Finland",
"Louisiana,US",
"Shanghai,China",
",Poland",
",Singapore",
",Luxembourg",
"Michigan,US",
",Iceland",
"Massachusetts,US",
"Hebei,China",
",Indonesia",
"New South Wales,Australia",
"Fujian,China",
"Georgia,US",
",Slovenia",
",Bahrain",
",Romania",
"Colorado,US",
",Saudi Arabia",
",Thailand",
",Estonia",
"Texas,US",
"Ontario,Canada",
",Egypt",
"Guangxi,China",
"Shaanxi,China",
",Chile",
",Peru",
"British Columbia,Canada",
",Philippines",
"Hong Kong,China",
"Pennsylvania,US",
",Ecuador",
",Russia",
",India",
",Iraq",
",Turkey",
"Yunnan,China",
"Hainan,China",
"Connecticut,US",
"Wisconsin,US",
",Lebanon",
"Tennessee,US",
",South Africa",
",Kuwait",
"Guizhou,China",
"Queensland,Australia",
",United Arab Emirates",
"Tianjin,China",
"Gansu,China",
"Shanxi,China",
"Liaoning,China",
",Slovakia",
"North Carolina,US",
"Victoria,Australia",
"Quebec,Canada",
"Alberta,Canada",
",San Marino",
"Ohio,US",
",Mexico",
",Armenia",
",Panama",
",Taiwan*",
"Maryland,US",
",Croatia",
",Serbia",
",Colombia",
"Virginia,US",
",Argentina",
"Nevada,US",
",Bulgaria",
"Jilin,China",
"Minnesota,US",
"Oregon,US",
",Algeria",
",Latvia",
",Vietnam",
"South Carolina,US",
"Utah,US",
",Uruguay",
"Alabama,US",
"Xinjiang,China",
",Brunei",
"Inner Mongolia,China",
"Ningxia,China",
",Hungary",
"Faroe Islands,Denmark",
",Costa Rica",
",Jordan",
",Cyprus",
",Albania",
",Bosnia and Herzegovina",
",Morocco",
"Arkansas,US",
",Sri Lanka",
"Indiana,US",
",Andorra",
",Malta",
"Western Australia,Australia",
"Maine,US",
",Belarus",
"Mississippi,US",
",Moldova",
",North Macedonia",
",Oman",
"Diamond Princess,US",
"Arizona,US",
",Azerbaijan",
",Kazakhstan",
"Iowa,US",
"New Hampshire,US",
"Oklahoma,US",
"Rhode Island,US",
"South Australia,Australia",
",Venezuela",
",Georgia",
"District of Columbia,US",
",Tunisia",
",Cambodia",
"Kentucky,US",
",Lithuania",
"New Mexico,US",
",Dominican Republic",
"Kansas,US",
",Burkina Faso",
",Guadeloupe",
",Senegal",
"Missouri,US",
"Delaware,US",
"Nebraska,US",
",Liechtenstein",
",New Zealand",
",Martinique",
",Uzbekistan",
",Afghanistan",
"Grand Princess,US",
"Vermont,US",
"Qinghai,China",
"North Dakota,US",
"Wyoming,US",
",Bangladesh",
"Manitoba,Canada",
"Macau,China",
"Saskatchewan,Canada",
"Hawaii,US",
",Ukraine",
",Jamaica",
"Nova Scotia,Canada",
",Congo (Kinshasa)",
",Reunion",
",Cameroon",
",Maldives",
",Bolivia",
",Honduras",
"Guam,US",
"New Brunswick,Canada",
",Cuba",
",French Guiana",
",Ghana",
",Paraguay",
"Idaho,US",
"Montana,US",
"South Dakota,US",
"Channel Islands,United Kingdom",
"Tasmania,Australia",
"Gibraltar,United Kingdom",
"Grand Princess,Canada",
",Cote d'Ivoire",
",Guatemala",
",Trinidad and Tobago",
"Alaska,US",
",Nigeria",
",Rwanda",
",Guyana",
",Kenya",
",Monaco",
",Equatorial Guinea",
",Ethiopia",
"French Polynesia,France",
",Mongolia",
",Seychelles",
",Tanzania",
",Barbados",
"Puerto Rico,US",
",Aruba",
"Australian Capital Territory,Australia",
"St Martin,France",
",Bahamas, The",
"Newfoundland and Labrador,Canada",
",Congo (Brazzaville)",
"Saint Barthelemy,France",
",Kyrgyzstan",
",Mauritius",
",Mayotte",
",Montenegro",
",Namibia",
"Curacao,Netherlands",
"Virgin Islands,US",
"Cayman Islands,United Kingdom",
",Benin",
"Prince Edward Island,Canada",
"Greenland,Denmark",
"New Caledonia,France",
",Kosovo",
",Liberia",
",Mauritania",
"Aruba,Netherlands",
",Saint Lucia",
",Sudan",
"United States Virgin Islands,US",
"West Virginia,US",
"Bermuda,United Kingdom",
",Zambia",
",Antigua and Barbuda",
"Northern Territory,Australia",
",Bhutan",
",Central African Republic",
",Chad",
"Tibet,China",
",Djibouti",
",El Salvador",
",Eswatini",
",Fiji",
",Gabon",
",Gambia, The",
",Guinea",
",Holy See",
",Nepal",
",Nicaragua",
",Saint Vincent and the Grenadines",
",Somalia",
",Suriname",
",Togo",
"US,US",
"Montserrat,United Kingdom",
"From Diamond Princess,Australia",
"French Guiana,France",
"Guadeloupe,France",
"Mayotte,France",
"Reunion,France",
",Greenland",
",Guam",
",Guernsey",
",Jersey",
",Puerto Rico",
",Republic of the Congo",
",The Bahamas",
",The Gambia"
];